spring.application.name=Job-Portal
spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb+srv://Samarth91:Samarthk91@cluster0.gbbzauz.mongodb.net/job-portal?appName=Cluster0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codewithsamarthk@gmail.com
spring.mail.password=ectnrionzcbznopi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

USER_FOUND= User already exist with this email.
USER_NOT_FOUND = User not found with this email.
INVALID_CREDENTIALS= Invalid credentials.
OTP_NOT_FOUND= OTP not found for this email.
OTP_INCORRECT= Incorrect OTP.
EMAIL_NOT_VERIFIED= Please verify your email before logging in.
RESUME_LIMIT_REACHED= You can upload a maximum of 5 resumes.
RESUME_NAME_EXISTS= A resume with this name already exists.
RESUME_NOT_FOUND= Resume not found.

# Google Gemini API
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
gemini.api.key=
